"""C-end (consumer-side) routes.

CONVENTION (per implementation-plan §2.3):
All C-end routes — regardless of their URL second segment — live in this
single file. That includes (but is not limited to) future routes:
  /api/user/upload, /api/styles, /api/recommend, /api/tryon,
  /api/tryon/batch, /api/tryon/:id, /api/events/collect.

DO NOT create separate files like styles.py / recommend.py / tryon.py /
events.py. The filename `user.py` is shorthand for "C-end router",
not "only routes under /api/user/*".

auth convention (per implementation-plan Step 4.1, authoritative):
- `user_id` is generated by the frontend (UUID v4) on first visit to
  /upload and stored in sessionStorage; it MUST be sent as the HTTP
  header `X-User-Id` on every /api/... request.
- `gender` ("female" | "male") is selected by the user on /gender and
  stored in sessionStorage; it is sent in the request BODY where relevant
  (recommend / tryon), NOT as a header.
- The backend keeps no session table — `X-User-Id` is the only identity
  surface. main.py's require_user_id middleware rejects any /api/... call
  (except /api/health) whose header is missing or not a legal UUID with
  `{code:400, msg:"invalid_user_id", data:null}`.
"""
from fastapi import APIRouter

from app.responses import ok

router = APIRouter(prefix="/api")


@router.get("/ping")
def ping():
    """Liveness probe for the C-end router. Plan §2.3 verification target."""
    return ok(data={"router": "user"})
